# Site Information
name:         Pongstagr.am jQuery Plugin
desc:         " is a jQuery plugin that lets display your instagram media to your website using Bootstrap Front-end styles and modal-plugin."

# Include/Exclude
include:      ['.htaccess']
exclude:      ['.gitignore', '*.sass-cache', 'scss', '*.txt', '*.rb', '*.md', '*.sh' ]

# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty
baseurl:      /

# Server
destination:  gh-pages
port:         4000

# Versions
version:     "v3.0.0"