# Site Information
name:         "Pongstagr.am"
desc:         "is a jQuery plugin that lets you display your Instagram media to your website using Bootstrap Front-end styles and modal-plugin."

author:       "Pongstr - Philip Ordillo"
description:  "Pongstagr.am is a jQuery plugin that lets you display Instagram media to your website"
keywords:     "jquery, instagram, github, pongstr, ordillo, philip, pongstagram, pongstagr"

# Include/Exclude
exclude:      ['.gitignore', '*.sass-cache', 'scss', '*.txt', '*.rb', '*.sh', '_images', 'node_modules', 'bower_components', 'Gruntfile.js', 'package.json' ]

# Dependencies
markdown:     kramdown
highlighter:  true

# Permalinks
permalink:    pretty
baseurl:      http://pongstr.github.io/pongstagr.am

# Server
source:       app
destination:  _gh_pages
port:         4001

# Versions
repourl:     "https://github.com/pongstr/pongstagr.am/"
version:     "4.0.0"
download:    "https://github.com/pongstr/pongstagr.am/archive/v3.1.9.zip"